version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
